defaults:
  - _self_

seed: 3

train:
  loss_weight:
    phys: 0

  log_every_n_steps: 1

  # NOTE: Set both to "false" to prevent accidental data overwriting or corrupting existing training progress
  continue_from_last_checkpoint: false        # Whether to continue training from last checkpoint
  force_overwrite: false                      # Overwrite existing checkpoint

  device: "cuda:0"

  output_path: null
